import { AuthAxios } from "./axiosConfig";

const dummyMed = [
  {
    id: 1,
    medName: "Panadol",
    medType: "tablet",
    potency: "200mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 2,
    drugQuantity: 500,
  },
  {
    id: 2,
    medName: "Panadol Extra",
    medType: "tablet",
    potency: "200mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 2,
    drugQuantity: 500,
  },
  {
    id: 3,
    medName: "Brufin",
    medType: "syrup",
    potency: null,
    manufacturer: "pfizzer",
    minimumUnit: 5,
    unitPrice: 1.5,
    drugQuantity: 2500,
  },
  {
    id: 4,
    medName: "Disprin",
    medType: "tablet",
    potency: "150mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 2,
    drugQuantity: 2400,
  },
  {
    id: 5,
    medName: "Permolin",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 6,
    medName: "Permolin12",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 7,
    medName: "Permolin14",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 8,
    medName: "Permolin18",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 9,
    medName: "Winston",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 10,
    medName: "Sinopharm",
    medType: "injection",
    potency: null,
    manufacturer: "pfizzer",
    minimumUnit: 6,
    unitPrice: 50,
    drugQuantity: 300,
  },
  {
    id: 11,
    medName: "Permolin0",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 12,
    medName: "Permolin11",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 13,
    medName: "Permolin12",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 14,
    medName: "Permolin312",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 15,
    medName: "Permolin1231",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 16,
    medName: "Permoli131n",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 17,
    medName: "Permolin1321",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 18,
    medName: "Permolin121234",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 19,
    medName: "Permolin12312313",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 20,
    medName: "Permolin lajhhb ayusgd",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 21,
    medName: "Permolin jkasjqwq",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 22,
    medName: "Permolin kjajndjn jansjdaasd",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 23,
    medName: "Permolin awqwwqdq",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 24,
    medName: "Permolinaweqwe",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 25,
    medName: "Permolin Wlqwq",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 26,
    medName: "Sentos",
    medType: "syrup",
    potency: null,
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 27,
    medName: "Zmolin",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 28,
    medName: "linwet",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 29,
    medName: "Toot Seya",
    medType: "syrup",
    potency: null,
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 30,
    medName: "Morolin",
    medType: "capsul",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 31,
    medName: "Sjsjsd",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 32,
    medName: "Srmolin",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 33,
    medName: "Permolin10",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 34,
    medName: "Pmolin",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 35,
    medName: "molin",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 36,
    medName: "Bermolin9",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 37,
    medName: "Permolin8",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 38,
    medName: "Permolin7",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 39,
    medName: "Permolin",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 40,
    medName: "Permolin6",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 41,
    medName: "Permolin5",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 42,
    medName: "Permolin4",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 43,
    medName: "Permolin3",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 44,
    medName: "Permolin2",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
  {
    id: 45,
    medName: "Permolin1",
    medType: "tablet",
    potency: "100mg",
    manufacturer: "pfizzer",
    minimumUnit: 1,
    unitPrice: 15,
    drugQuantity: 300,
  },
];

export function getMedicines() {
  //return AuthAxios.get("/projects");
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({ data: dummyMed });
      //reject({ errors: ["Some server error occur in fetching"] });
    }, 1000);
  });
}

export function addMedicine(values) {
  const medData = {
    medName: values.medName,
    potency: values.potency,
    medType: values.medType,
    minimumUnit: values.minimumUnit,
    unitPrice: values.unitPrice,
    manufacturer: values.manufacturer,
  };

  const batchData = {
    batchNum: values.batchNum,
    totalQuantity: values.totalQuantity,
    amountPaid: values.amountPaid,
    manuDate: values.manuDate,
    expiryDate: values.expiryDate,
  };

  const bodyData = {
    medData: medData,
    batchData: batchData,
  };
  return AuthAxios.post("/medicine/add", bodyData);
}
